-- SQLite
SELECT  LOCATIONS.START_DATE,
        LOCATIONS.END_DATE,
        LOCATIONS.TOTAL,
        CUSTOMERS.NAME AS 'Nome do Cliente',
        CARS.NAME AS 'Nome do Carro',
        EMPLOYEES.NAME AS 'Nome do Funcionário'

FROM LOCATIONS
  INNER JOIN CUSTOMERS ON (LOCATIONS.CUSTOMER_ID = CUSTOMERS.ID)
  INNER JOIN CARS ON (LOCATIONS.CAR_ID = CARS.ID)
  INNER JOIN EMPLOYEES ON (LOCATIONS.EMPLOYEE_ID = EMPLOYEES.ID);